// Parent-Child Connection Activities
// Keyed by lesson_id — focused on connection, communication, and self-worth

export const ACTIVITIES = {
  1: [
    {
      title: "Their World in a Box",
      emoji: "📦",
      goal: "Connection & communication",
      duration: "30 min",
      description: "Together, fill a small box with 5-7 objects that tell your child's story — things they love, things that make them feel safe, things from their past. No judgment, just curiosity. Let your child lead.",
      prompt: "Ask: \"If someone wanted to know who you really are, what would you put in this box?\"",
      materials: "Any small box, random objects from around the house",
    },
    {
      title: "\"Hard Places\" Artwork",
      emoji: "🎨",
      goal: "Self-worth & emotional expression",
      duration: "20 min",
      description: "Draw two images side by side: one of a 'hard place' (doesn't have to be literal — could be a weather picture, a color, a shape), and one of a 'safe place.' Share yours too — this is a together activity.",
      prompt: "Say: \"Everyone has hard places. Yours don't define you — they're part of your story.\"",
      materials: "Paper, crayons/markers",
    },
  ],
  2: [
    {
      title: "Brain Volcano",
      emoji: "🌋",
      goal: "Communication & emotional literacy",
      duration: "15 min",
      description: "Draw a volcano together. The magma at the bottom = the feeling (fear, shame, sadness). The eruption = the behavior (yelling, hitting, running). Talk about what's happening at each level — without blame.",
      prompt: "Ask: \"What's usually in the magma for you? What does it feel like before the eruption?\"",
      materials: "Paper, colored pens",
    },
    {
      title: "Calm vs. Activated Body Scan",
      emoji: "🧘",
      goal: "Self-awareness & regulation",
      duration: "10 min",
      description: "Sit together and take turns describing what your body feels like when calm (soft belly, slow breath) and when activated (tight chest, fast heart). No fixing, just noticing. Make it a game — guess which state the other person is in.",
      prompt: "Say: \"Our bodies talk to us. Learning the language is a superpower.\"",
      materials: "None needed",
    },
  ],
  3: [
    {
      title: "Special Handshake",
      emoji: "🤝",
      goal: "Connection ritual",
      duration: "10 min",
      description: "Create a unique handshake together — the sillier the better. Include at least 5 steps. Use it every morning, every goodbye, every reunion. Rituals build felt safety through predictability and delight.",
      prompt: "Say: \"This handshake belongs only to us.\"",
      materials: "None",
    },
    {
      title: "Rose, Thorn, Bud",
      emoji: "🌹",
      goal: "Communication & connection",
      duration: "10 min daily",
      description: "At dinner or bedtime: each person shares a Rose (something good today), a Thorn (something hard), and a Bud (something you're looking forward to). No advice, no fixing — just listening.",
      prompt: "Rule: the listener only says 'thank you for sharing that.' No problem-solving.",
      materials: "None",
    },
  ],
  4: [
    {
      title: "Safety Map",
      emoji: "🗺️",
      goal: "Felt safety & communication",
      duration: "20 min",
      description: "Draw a map of your home together. Mark the 'safe spots' — places your child can go when they feel overwhelmed. Agree on what those spaces mean (no interrupting, no consequences in that spot). Make it their own.",
      prompt: "Say: \"Everyone needs a place to land. Where's yours?\"",
      materials: "Paper, markers",
    },
    {
      title: "Transition Warning Practice",
      emoji: "⏰",
      goal: "Felt safety & cooperation",
      duration: "5 min (ongoing)",
      description: "For one full day, practice giving 10-minute and 5-minute warnings before every transition. Notice how your child's body responds differently. At the end of the day, ask them how the warnings felt.",
      prompt: "Ask: \"Did it feel different when you knew what was coming?\"",
      materials: "A timer",
    },
  ],
  5: [
    {
      title: "HALT Check-In Card",
      emoji: "✋",
      goal: "Self-awareness & communication",
      duration: "15 min to make, ongoing use",
      description: "Together, create a laminated or drawn 'HALT Card' — Hungry, Anxious, Lonely, Tired. Decorate it together. Teach your child to ask themselves (and you!) before a hard moment: 'What am I right now?'",
      prompt: "Say: \"Even I need to check this. Let's check in with each other.\"",
      materials: "Card, markers, optional laminator",
    },
    {
      title: "Movement Break Jar",
      emoji: "🫙",
      goal: "Regulation & self-worth",
      duration: "20 min to create",
      description: "Fill a jar with slips of paper — each one has a movement activity (hop 20 times, do 10 wall push-ups, shake your whole body for 30 seconds). When energy is high, pull one slip together. The parent does it too.",
      prompt: "Say: \"Bodies hold feelings. Sometimes we need to move them out.\"",
      materials: "Jar, paper slips, markers",
    },
  ],
  6: [
    {
      title: "Life Values Poster",
      emoji: "🖼️",
      goal: "Self-worth & identity",
      duration: "30 min",
      description: "Together, make a large poster with one life value in the center (Trustworthy, Kind, Responsible, Respectful, Self-controlled). Around it, your child draws or writes examples of themselves living that value. Hang it where they can see it.",
      prompt: "Say: \"I see you being [value] when you ___. I want to remember that.\"",
      materials: "Poster board, markers, stickers",
    },
    {
      title: "Role Play the Redo",
      emoji: "🎭",
      goal: "Communication & skill-building",
      duration: "15 min",
      description: "Act out a scene where someone makes a poor choice — you can be the child, let them be the parent. Then redo the scene with the better choice. Keep it playful and swap roles. Laugh together.",
      prompt: "Say: \"Practice makes the brain stronger. Let's try it again — different ending this time.\"",
      materials: "None",
    },
  ],
  7: [
    {
      title: "Choices Board",
      emoji: "📋",
      goal: "Self-worth & empowerment",
      duration: "20 min",
      description: "Create a 'choices board' for one daily routine (getting ready, homework, bedtime). Your child picks the order of tasks from a list. The tasks are non-negotiable; the order is their choice. Hang it up and use it.",
      prompt: "Say: \"I trust you to make good choices in the order that works for you.\"",
      materials: "Cardstock, velcro or magnets for moveable pieces",
    },
    {
      title: "Worry Doll / Worry Jar",
      emoji: "🏺",
      goal: "Communication & anxiety release",
      duration: "15 min",
      description: "Together, make a simple 'worry jar.' Each night, write or draw one worry on a slip of paper and put it in the jar. Once a week, open the jar together and check: has the worry changed? Is it still a worry? Celebrate the ones that dissolved.",
      prompt: "Say: \"Your worries are real. I want to hold them with you.\"",
      materials: "Jar, paper, pens",
    },
  ],
  8: [
    {
      title: "Redo Role Play — Parent Version",
      emoji: "🔄",
      goal: "Repair & connection",
      duration: "15 min",
      description: "Act out a recent moment that didn't go well — this time, the parent models a Redo. 'Let me try that again.' Show your child that adults can redo too. Invite them to coach you on how to do it better.",
      prompt: "Ask: \"Was that better? What else could I have done?\" Let them guide you.",
      materials: "None",
    },
    {
      title: "Calm-Down Kit Together",
      emoji: "🧰",
      goal: "Regulation & self-worth",
      duration: "25 min",
      description: "Build a calm-down kit together — a bag or box with 5-7 items your child chooses that help them feel better (stress ball, drawing pad, headphones, a smooth rock, a comfort scent). Decorate the bag. Keep it in the safety spot.",
      prompt: "Say: \"You know yourself better than anyone. What helps you feel better?\"",
      materials: "Bag/box, various sensory items",
    },
  ],
  9: [
    {
      title: "\"When I Was Little\" Story Swap",
      emoji: "📖",
      goal: "Connection & identity",
      duration: "20 min",
      description: "Take turns telling stories about when you were your child's age — what you were afraid of, what made you happy, what you struggled with. Be honest and age-appropriate. Let your child ask questions about your childhood.",
      prompt: "Say: \"I want you to know me — not just as your parent, but as a person who was also a kid once.\"",
      materials: "None",
    },
    {
      title: "PACE Mirror Game",
      emoji: "🪞",
      goal: "Connection & empathy",
      duration: "10 min",
      description: "Sit across from each other and mirror each other's movements for 3 minutes — one leads, one mirrors. Then switch. No talking. Afterward, talk about how it felt to be followed so carefully, and to follow someone else.",
      prompt: "Say: \"When I follow you, I'm saying: you matter. I'm paying attention.\"",
      materials: "None",
    },
  ],
  10: [
    {
      title: "Feelings Faces Book",
      emoji: "😊",
      goal: "Emotional literacy & communication",
      duration: "30 min",
      description: "Create a small book together — each page has a feeling word, a drawing of a face showing that feeling, and a sentence: 'I feel ___ when ___.' Include big feelings AND small feelings. Keep it on the shelf as a reference.",
      prompt: "Say: \"All feelings are allowed here. We just practice what we do with them.\"",
      materials: "Blank paper stapled together, markers",
    },
    {
      title: "Curiosity Questions Jar",
      emoji: "❓",
      goal: "Communication & connection",
      duration: "Ongoing",
      description: "Fill a jar with curiosity questions — non-threatening, imaginative, playful. Pull one each day. Examples: 'If you could add one rule to our family, what would it be?' 'What's one thing you wish I understood about you?'",
      prompt: "Rule: no judgment, no lectures. Just listen and ask follow-up questions.",
      materials: "Jar, paper slips",
    },
  ],
  11: [
    {
      title: "Sensory Treasure Hunt",
      emoji: "🔍",
      goal: "Connection & sensory awareness",
      duration: "20 min",
      description: "Walk through your home together and find: something soft, something rough, something cold, something that smells good, something that makes a calming sound. Talk about what each of you notices. No wrong answers.",
      prompt: "Say: \"Our bodies notice different things. Both are true.\"",
      materials: "None",
    },
    {
      title: "Build the Calm-Down Toolkit",
      emoji: "🎒",
      goal: "Self-regulation & self-worth",
      duration: "30 min",
      description: "Go on a 'sensory shopping trip' around the house — fill a bag together with tools for calming (heavy blanket, textured toy, lavender-scented cloth, crunchy snack). Let your child be the expert on what works for their body.",
      prompt: "Ask: \"What does your body need when it gets too loud inside?\"",
      materials: "Any bag, sensory items from home",
    },
  ],
  12: [
    {
      title: "The Little You Activity",
      emoji: "👶",
      goal: "Self-worth & compassion",
      duration: "20 min",
      description: "Look at a photo of your child when they were younger (or draw a little version of them). Talk about what that little version needed — to feel safe, to be held, to be seen. Let your child practice offering compassion to 'little them.'",
      prompt: "Say: \"That little person needed so much. And they grew up brave.\"",
      materials: "A photo if available, or drawing materials",
    },
    {
      title: "You Were Once My Age",
      emoji: "🕰️",
      goal: "Connection & identity",
      duration: "15 min",
      description: "Tell your child what you needed as a child the same age they are now. Be honest. Then ask: 'What do you need at your age?' Listen without advice.",
      prompt: "Say: \"You and I aren't so different. Needs change, but they never go away.\"",
      materials: "None",
    },
  ],
  13: [
    {
      title: "Abundance Pantry Project",
      emoji: "🍎",
      goal: "Felt safety & connection",
      duration: "30 min",
      description: "Together, stock a small basket or shelf with snacks — and let your child know: 'This is always here. For you. Anytime.' Let them help choose what goes in it, label it with their name, and keep it full. Discuss together what 'enough' feels like.",
      prompt: "Say: \"You will always have enough here. I want your body to know that.\"",
      materials: "Basket, snacks, name label",
    },
    {
      title: "Truth Is Safe Here",
      emoji: "🕊️",
      goal: "Communication & trust",
      duration: "15 min",
      description: "Create a 'truth agreement' together — a simple written or drawn document that says: in this home, the truth is safer than a lie. Define together what happens when truth is told (empathy first, then problem-solving). Sign it together.",
      prompt: "Say: \"I want you to trust that telling me the truth is safe. I'm practicing that with you.\"",
      materials: "Paper, pens",
    },
  ],
  14: [
    {
      title: "The Feelings Behind the Behavior",
      emoji: "🧩",
      goal: "Communication & empathy",
      duration: "20 min",
      description: "Together, draw a 'feelings iceberg' — the behavior above the waterline (hitting, yelling, running), the feelings below it (scared, ashamed, alone). Talk about what's underneath for each of you — no current incidents, just in general.",
      prompt: "Say: \"What people see isn't always what's real. I want to know what's underneath for you.\"",
      materials: "Paper, markers",
    },
    {
      title: "Safe Space Design",
      emoji: "🏠",
      goal: "Felt safety & self-worth",
      duration: "25 min",
      description: "Let your child design (on paper or in real life) their ideal calm-down space in the house. What would be in it? What would the rules be? Then help make it happen — even partially. Having agency over a space builds felt safety.",
      prompt: "Say: \"You deserve a place that belongs to you. Let's create it together.\"",
      materials: "Paper, markers, optional craft/decorating supplies",
    },
  ],
  15: [
    {
      title: "Our Family Advocate Chart",
      emoji: "📣",
      goal: "Identity & empowerment",
      duration: "20 min",
      description: "Draw a chart together listing everyone who is 'on your family's team' — name, role, and why they matter. Include professionals, family, and community members. Talk about who your child can go to if they need help.",
      prompt: "Say: \"You are not alone. Look at all the people who care about you.\"",
      materials: "Large paper, markers",
    },
    {
      title: "I Know My Rights",
      emoji: "⚖️",
      goal: "Self-worth & empowerment",
      duration: "15 min",
      description: "Teach your child (age-appropriately) a few things they have the right to: to be safe, to know what's happening, to ask questions, to feel their feelings, to make age-appropriate choices. Write them out together. Let them decorate it.",
      prompt: "Say: \"You have rights. I want you to know them and believe them.\"",
      materials: "Paper, markers",
    },
  ],
  16: [
    {
      title: "Our Village Map",
      emoji: "🌎",
      goal: "Connection & belonging",
      duration: "20 min",
      description: "Together, draw a 'village map' — your home in the center, surrounded by all the people in your support circle. Include professionals, neighbors, family, friends. Talk about who each person is and what they offer.",
      prompt: "Say: \"Everybody needs a village. Ours looks like this.\"",
      materials: "Large paper, markers",
    },
    {
      title: "Letter to a Friend",
      emoji: "✉️",
      goal: "Self-worth & expression",
      duration: "15 min",
      description: "Each of you writes a letter to an imaginary friend who is going through a hard time — offering advice, warmth, and encouragement. Share the letters with each other. Notice how wise and kind you both are.",
      prompt: "Say: \"You just gave someone exactly what you also deserve.\"",
      materials: "Paper, pens",
    },
  ],
  17: [
    {
      title: "Caregiver Care Card",
      emoji: "💌",
      goal: "Connection & mutual care",
      duration: "15 min",
      description: "Your child makes a card for YOU — listing things they love about you, or things that help you feel better. You make one for them. Exchange. Talk about how taking care of each other is a two-way thing.",
      prompt: "Say: \"You take care of me too — even when you don't know it.\"",
      materials: "Card-making supplies",
    },
    {
      title: "Rest Ritual",
      emoji: "🌙",
      goal: "Regulation & connection",
      duration: "10 min daily",
      description: "Create a simple wind-down ritual together (5-minute back rub, reading two pages together, one thing you're grateful for). Commit to it for 7 nights. No screens, no stimulation — just presence and transition to rest.",
      prompt: "Say: \"Rest is when we heal. I want to help your body learn how.\"",
      materials: "None",
    },
  ],
  18: [
    {
      title: "The Repair Letter",
      emoji: "🌈",
      goal: "Repair & connection",
      duration: "20 min",
      description: "Together, choose a recent hard moment. Each person writes (or draws) a short note: what happened, what they felt, what they wish had gone differently, and what they want the other person to know. Exchange notes. No debate — just receive.",
      prompt: "Say: \"We both did hard things. I want us to come back from it together.\"",
      materials: "Paper, pens",
    },
    {
      title: "Reconnect Ritual",
      emoji: "🔗",
      goal: "Repair & connection",
      duration: "15 min",
      description: "After a hard moment has passed, have a go-to 'reconnect activity' — something you both enjoy (puzzles, drawing, a walk, cooking something simple). No talking about the incident. Just being together peacefully.",
      prompt: "Say: \"We can always come back to each other. That's our commitment.\"",
      materials: "Whatever your reconnect activity requires",
    },
  ],
  19: [
    {
      title: "My Story Timeline",
      emoji: "📅",
      goal: "Identity & self-worth",
      duration: "30 min",
      description: "Create a timeline of your child's life together — include hard things AND good things. Label each point with what your child survived, learned, or gained. End with today and 'what comes next.' Frame it as a hero's journey.",
      prompt: "Say: \"Every part of your story matters. Look how far you've come.\"",
      materials: "Long paper or taped-together sheets, markers",
    },
    {
      title: "Who Loves Me Web",
      emoji: "🕸️",
      goal: "Self-worth & belonging",
      duration: "15 min",
      description: "Write your child's name in the center of a paper. Draw lines to everyone who loves or cares for them — alive or not, near or far. Fill the page. Keep it somewhere visible.",
      prompt: "Say: \"Love doesn't run out. You have more of it than you know.\"",
      materials: "Paper, markers",
    },
  ],
  20: [
    {
      title: "Strengths Collage",
      emoji: "💪",
      goal: "Self-worth & identity",
      duration: "30 min",
      description: "Cut out or draw images that represent your child's strengths — things they're good at, things they've survived, things they love. Create a collage together. Frame it or hang it in their room.",
      prompt: "Say: \"These are real. These belong to you. Nobody can take them.\"",
      materials: "Magazines or printed images, glue, paper",
    },
    {
      title: "Letter From Future Me",
      emoji: "🚀",
      goal: "Hope & self-worth",
      duration: "20 min",
      description: "Each of you writes a letter from your future self — 10 years from now — back to your present self. What has the future self learned? What are they proud of? What would they say about right now?",
      prompt: "Say: \"Your future is still being written. And it can be good.\"",
      materials: "Paper, envelopes (optional: seal and open in a year)",
    },
  ],
  21: [
    {
      title: "Family Mission Statement",
      emoji: "📜",
      goal: "Identity, connection & self-worth",
      duration: "30 min",
      description: "Together, write 3-5 sentences describing what your family stands for, what you believe, and how you want to treat each other. Decorate it. Frame it. Review it together once a month.",
      prompt: "Ask: \"What do we believe about people? About hard times? About each other?\"",
      materials: "Paper, markers, optional frame",
    },
    {
      title: "Celebration Ritual",
      emoji: "🎉",
      goal: "Self-worth & connection",
      duration: "20 min",
      description: "Create a family celebration tradition for finishing hard things — a special meal, a dance, a 'we did it' banner. Celebrate completing the HALO program together right now. Mark it. Make it real.",
      prompt: "Say: \"You worked hard. We worked hard. That deserves to be celebrated.\"",
      materials: "Whatever your celebration requires",
    },
  ],
};