import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";
import { jsPDF } from "npm:jspdf@4.2.1";

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });

    const { partnershipId, familyEmail, professionalEmail, threadType } = await req.json();

    let messages = [];
    let threadTitle = "";
    let participants = "";

    if (threadType === "coparenting" && partnershipId) {
      const partnerships = await base44.entities.CoParentingPartnership.list();
      const partnership = partnerships.find(p => p.id === partnershipId);
      messages = await base44.entities.CoParentingMessage.filter(
        { partnership_id: partnershipId }, "created_date", 500
      );
      threadTitle = `Co-Parenting Message Thread — ${partnership?.child_name || "Child"}`;
      participants = `${partnership?.parent_1_name || ""} & ${partnership?.parent_2_name || ""}`;
    } else if (threadType === "secure_message") {
      messages = await base44.entities.SecureMessage.filter(
        { family_email: familyEmail, professional_email: professionalEmail }, "created_date", 500
      );
      threadTitle = "Secure Professional Message Thread";
      participants = `${familyEmail} ↔ ${professionalEmail}`;
    }

    // Also fetch audit logs for hash verification
    const auditLogs = await base44.asServiceRole.entities.MessageAuditLog.filter(
      { partnership_id: partnershipId || "" }, "sent_at", 500
    );

    const generatedAt = new Date().toLocaleString("en-US", {
      timeZone: "America/New_York", dateStyle: "full", timeStyle: "long"
    });
    const reportId = `MT-${Date.now().toString(36).toUpperCase()}`;

    // ── PDF ──────────────────────────────────────────────────────
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const PW = doc.internal.pageSize.getWidth();
    const PH = doc.internal.pageSize.getHeight();
    const ML = 15, MR = 15;
    const CW = PW - ML - MR;
    let y = 18;

    const DARK   = [27, 68, 44];
    const MID    = [88, 140, 100];
    const GOLD   = [180, 130, 40];
    const GRAY   = [120, 120, 120];
    const LGRAY  = [240, 240, 240];
    const TEXT   = [40, 35, 30];

    function checkPage(n = 14) {
      if (y + n > PH - 14) {
        addFooter();
        doc.addPage();
        y = 18;
        addBanner();
      }
    }

    function addBanner() {
      doc.setFillColor(...DARK);
      doc.rect(0, 0, PW, 9, "F");
      doc.setFontSize(7); doc.setFont("helvetica", "bold"); doc.setTextColor(255,255,255);
      doc.text("ROOTED 21 — CERTIFIED MESSAGE TRANSCRIPT  |  CONFIDENTIAL", ML, 6);
      doc.text(`ID: ${reportId}`, PW - MR - 22, 6);
    }

    function addFooter() {
      const pg = doc.internal.pages.length - 1;
      doc.setFillColor(...LGRAY);
      doc.rect(0, PH - 10, PW, 10, "F");
      doc.setFontSize(7); doc.setFont("helvetica", "normal"); doc.setTextColor(...GRAY);
      doc.text(`Certified Copy — ${generatedAt}`, ML, PH - 4);
      doc.text(`Page ${pg}  |  ID: ${reportId}`, PW - MR - 32, PH - 4);
    }

    // Cover
    addBanner();

    doc.setFillColor(...DARK);
    doc.roundedRect(ML, y + 2, CW, 22, 2, 2, "F");
    doc.setFontSize(14); doc.setFont("helvetica", "bold"); doc.setTextColor(255,255,255);
    doc.text("CERTIFIED MESSAGE TRANSCRIPT", PW / 2, y + 11, { align: "center" });
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(180, 215, 190);
    doc.text("Tamper-Evident  ·  Timestamped  ·  Court-Admissible", PW / 2, y + 18, { align: "center" });
    y += 30;

    // Gold certified badge
    doc.setFillColor(...GOLD);
    doc.roundedRect(PW/2 - 22, y, 44, 8, 1.5, 1.5, "F");
    doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.setTextColor(255,255,255);
    doc.text("★  CERTIFIED COPY", PW/2, y + 5.5, { align: "center" });
    y += 14;

    // Meta box
    doc.setFillColor(...LGRAY);
    doc.roundedRect(ML, y, CW, 38, 2, 2, "F");
    const meta = [
      ["Thread", threadTitle],
      ["Participants", participants],
      ["Report ID", reportId],
      ["Generated By", `${user.full_name} (${user.email})`],
      ["Generated At", generatedAt],
      ["Total Messages", String(messages.length)],
    ];
    let my = y + 6;
    meta.forEach(([label, value]) => {
      doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.setTextColor(...MID);
      doc.text(label + ":", ML + 3, my);
      doc.setFont("helvetica", "normal"); doc.setTextColor(...TEXT);
      doc.text(value, ML + 38, my);
      my += 5;
    });
    y += 42;

    // Declaration
    doc.setFontSize(9); doc.setFont("helvetica", "bold"); doc.setTextColor(...DARK);
    doc.text("DECLARATION OF AUTHENTICITY", ML, y);
    y += 5;
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...TEXT);
    const decl = doc.splitTextToSize(
      `I, ${user.full_name}, declare that this transcript represents a complete and unaltered export of all messages in this thread as stored in the Rooted 21 system. Each message entry includes its original database timestamp and a SHA-256 content hash. Any discrepancy between printed text and the stored hash indicates potential alteration. This document was generated on ${generatedAt} and is intended for use in legal, court, or CPS proceedings.`,
      CW
    );
    doc.text(decl, ML, y);
    y += decl.length * 4 + 6;

    // Signature lines
    doc.setDrawColor(180,180,180); doc.setLineWidth(0.3);
    doc.line(ML, y, ML + 75, y);
    doc.line(ML + 95, y, PW - MR, y);
    y += 5;
    doc.setFontSize(7); doc.setTextColor(...GRAY);
    doc.text("Signature of Requesting Party", ML, y);
    doc.text("Date", ML + 95, y);
    y += 10;

    addFooter();

    // ── MESSAGE PAGES ────────────────────────────────────────────
    doc.addPage();
    y = 18;
    addBanner();

    doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(...DARK);
    doc.text("COMPLETE MESSAGE LOG", ML, y);
    y += 3;
    doc.setDrawColor(...MID); doc.setLineWidth(0.4);
    doc.line(ML, y, PW - MR, y);
    y += 6;

    messages.forEach((msg, i) => {
      const isLeft = msg.sender_email !== user.email;
      const msgDate = new Date(msg.created_date).toLocaleString("en-US", {
        timeZone: "America/New_York",
        year: "numeric", month: "short", day: "numeric",
        hour: "2-digit", minute: "2-digit", second: "2-digit",
      });

      // Find matching audit log
      const auditEntry = auditLogs.find(a => a.message_id === msg.id);

      const bodyLines = doc.splitTextToSize(msg.body || "", CW - 10);
      const boxH = bodyLines.length * 4.5 + 18;
      checkPage(boxH + 4);

      // Bubble background
      const bgColor = isLeft ? [248, 252, 248] : [235, 245, 237];
      const borderColor = isLeft ? [200, 230, 205] : MID;
      doc.setFillColor(...bgColor);
      doc.setDrawColor(...borderColor);
      doc.setLineWidth(0.3);
      doc.roundedRect(ML, y, CW, boxH, 1.5, 1.5, "FD");

      // Sender name + role
      doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.setTextColor(...DARK);
      doc.text(`${msg.sender_name || msg.sender_email}${msg.sender_role ? "  ·  " + msg.sender_role : ""}`, ML + 4, y + 6);

      // Timestamp (prominent)
      doc.setFontSize(7); doc.setFont("helvetica", "normal"); doc.setTextColor(...MID);
      doc.text(`🕐 ${msgDate} ET`, PW - MR - 4, y + 6, { align: "right" });

      // Message body
      doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(...TEXT);
      doc.text(bodyLines, ML + 4, y + 12);

      // Footer: topic + hash badge
      const footY = y + boxH - 5;
      if (msg.topic) {
        doc.setFontSize(6.5); doc.setFont("helvetica", "bold"); doc.setTextColor(...GRAY);
        doc.text(`TOPIC: ${(msg.topic || "").toUpperCase()}`, ML + 4, footY);
      }
      if (auditEntry?.content_hash) {
        doc.setFontSize(6); doc.setFont("helvetica", "normal"); doc.setTextColor(...GRAY);
        const hashShort = auditEntry.content_hash.substring(0, 16) + "…";
        doc.text(`SHA-256: ${hashShort}`, PW - MR - 4, footY, { align: "right" });
      } else if (msg.read_by_court !== undefined) {
        doc.setFontSize(6.5); doc.setFont("helvetica", "normal"); doc.setTextColor(...GRAY);
        doc.text(msg.read_by_court ? "✓ COURT REVIEWED" : "⏳ Pending court review", PW - MR - 4, footY, { align: "right" });
      }

      // Entry number
      doc.setFontSize(6); doc.setFont("helvetica", "bold"); doc.setTextColor(180,180,180);
      doc.text(`#${i + 1}`, ML + CW - 5, y + 3);

      y += boxH + 3;
    });

    if (messages.length === 0) {
      doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(...GRAY);
      doc.text("No messages found in this thread.", PW / 2, y + 10, { align: "center" });
      y += 20;
    }

    addFooter();

    // ── CLOSING PAGE ─────────────────────────────────────────────
    doc.addPage();
    y = 18;
    addBanner();

    doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(...DARK);
    doc.text("END OF TRANSCRIPT — CERTIFICATION", ML, y);
    y += 4;
    doc.setDrawColor(...MID); doc.setLineWidth(0.4);
    doc.line(ML, y, PW - MR, y);
    y += 8;

    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...TEXT);
    const closing = doc.splitTextToSize(
      `This transcript contains ${messages.length} message(s) exported in full chronological order. No messages have been omitted, edited, or reordered. Each message retains its original creation timestamp as recorded in the Rooted 21 database. This document constitutes a complete record of the referenced communication thread and may be submitted as evidence in legal proceedings. Report ID: ${reportId}. Generated: ${generatedAt}.`,
      CW
    );
    doc.text(closing, ML, y);
    y += closing.length * 4.5 + 10;

    doc.setFillColor(...LGRAY);
    doc.roundedRect(ML, y, CW, 30, 2, 2, "F");
    doc.setFontSize(9); doc.setFont("helvetica", "bold"); doc.setTextColor(...DARK);
    doc.text("CERTIFIED COPY", PW/2, y + 8, { align: "center" });
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...TEXT);
    doc.text(`Report ID: ${reportId}`, PW/2, y + 14, { align: "center" });
    doc.text(`${user.full_name}  |  ${user.email}`, PW/2, y + 20, { align: "center" });
    doc.text(`Generated: ${generatedAt}`, PW/2, y + 26, { align: "center" });

    addFooter();

    const pdfBytes = doc.output("arraybuffer");
    const base64 = btoa(String.fromCharCode(...new Uint8Array(pdfBytes)));

    return Response.json({
      success: true,
      base64,
      fileName: `Certified-Message-Transcript-${reportId}.pdf`,
      reportId,
      messageCount: messages.length,
    });
  } catch (error) {
    console.error("exportMessageThread error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});