import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.2.1';

function safe(value) {
  return String(value || '').replace(/[\r\n]+/g, ' ').slice(0, 220);
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const payload = await req.json();
    const records = await base44.entities.CourtGradeRecord.filter({ owner_email: user.email }, '-submitted_at', 500);
    const filtered = payload.case_number
      ? records.filter(record => record.case_number === payload.case_number)
      : records;

    const doc = new jsPDF();
    const exportId = `R21-CERT-${Date.now().toString(36).toUpperCase()}`;
    let y = 18;

    doc.setFontSize(18);
    doc.text('Rooted 21 Certified Unalterable Record', 14, y);
    y += 8;
    doc.setFontSize(9);
    doc.text(`Export ID: ${exportId}`, 14, y);
    y += 5;
    doc.text(`Generated: ${new Date().toISOString()}`, 14, y);
    y += 5;
    doc.text(`Generated by: ${user.email}`, 14, y);
    y += 8;

    doc.setFontSize(10);
    doc.text('Certification Notice:', 14, y);
    y += 5;
    const notice = doc.splitTextToSize('This packet is generated from append-only records. Submitted entries include timestamps, verification IDs, and record hashes. Records are not editable or deletable inside the app after submission.', 182);
    doc.text(notice, 14, y);
    y += notice.length * 5 + 6;

    filtered.forEach((record, index) => {
      if (y > 255) {
        doc.addPage();
        y = 18;
      }
      doc.setFontSize(11);
      doc.text(`${index + 1}. ${safe(record.title)}`, 14, y);
      y += 5;
      doc.setFontSize(8);
      const lines = [
        `Type: ${record.record_type}`,
        `Occurred: ${record.occurred_at || 'Not listed'}`,
        `Submitted: ${record.submitted_at}`,
        `Verification ID: ${record.verification_id}`,
        `Record Hash: ${record.record_hash}`,
        record.child_name ? `Child: ${safe(record.child_name)}` : '',
        record.case_number ? `Case: ${safe(record.case_number)}` : '',
        record.attendance_status !== 'not_applicable' ? `Attendance: ${record.attendance_status}` : '',
        record.completion_status !== 'not_applicable' ? `Case-plan status: ${record.completion_status}` : '',
        record.milestone_status !== 'not_applicable' ? `Milestone status: ${record.milestone_status}` : '',
        record.gps_latitude ? `GPS: ${record.gps_latitude}, ${record.gps_longitude} accuracy ${record.gps_accuracy_meters || ''}m` : ''
      ].filter(Boolean);
      lines.forEach(line => {
        doc.text(line, 18, y);
        y += 4;
      });
      const detailLines = doc.splitTextToSize(`Details: ${safe(record.details)}`, 176);
      doc.text(detailLines, 18, y);
      y += detailLines.length * 4 + 5;
    });

    const bytes = doc.output('arraybuffer');
    return new Response(bytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=${exportId}.pdf`
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});