import { useState } from "react";
import { Link } from "react-router-dom";
import { C } from "@/lib/rooted-constants";
import { Shield, CheckCircle2, AlertTriangle, X } from "lucide-react";

const CONSENT_KEY = "rooted21_ai_consent_v1";

export function hasAIConsent() {
  try {
    const stored = JSON.parse(localStorage.getItem(CONSENT_KEY) || "null");
    return stored?.accepted === true;
  } catch {
    return false;
  }
}

export function recordAIConsent(userEmail) {
  localStorage.setItem(CONSENT_KEY, JSON.stringify({
    accepted: true,
    email: userEmail,
    timestamp: new Date().toISOString(),
  }));
}

const DISCLOSURES = [
  {
    emoji: "ℹ️",
    title: "Informational support only",
    body: "Rooted 21's AI is an educational parenting support tool. It is NOT a licensed therapist, medical provider, or attorney.",
  },
  {
    emoji: "🚫",
    title: "Not medical or therapeutic advice",
    body: "AI responses do not constitute a diagnosis, treatment plan, medication recommendation, or mental health assessment. Always consult a licensed professional for clinical decisions.",
  },
  {
    emoji: "⚖️",
    title: "Not legal advice",
    body: "Nothing generated by the AI constitutes legal advice or legal strategy. For legal matters, consult a licensed Ohio attorney.",
  },
  {
    emoji: "🆘",
    title: "In a crisis — contact emergency services",
    body: "The AI cannot replace emergency response. If you or your child are in danger, call 911. For mental health crises, call or text 988.",
  },
  {
    emoji: "💬",
    title: "Your conversations are private",
    body: "General AI chat history is private to your account. Co-Parent Portal messages are separately monitored per those terms.",
  },
];

export default function AIConsentModal({ user, onAccept }) {
  const [checked, setChecked] = useState(false);

  function handleAccept() {
    if (!checked) return;
    recordAIConsent(user?.email || "");
    onAccept();
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4"
      style={{ background: "rgba(0,0,0,0.65)", backdropFilter: "blur(4px)" }}
    >
      <div
        className="w-full sm:max-w-[480px] rounded-t-3xl sm:rounded-2xl overflow-hidden"
        style={{ background: C.offWhite, maxHeight: "92vh", overflowY: "auto" }}
      >
        {/* Header */}
        <div className="px-5 py-4 flex items-center gap-3" style={{ background: C.darkGreen }}>
          <Shield size={20} color={C.gold} />
          <div className="flex-1">
            <p className="font-serif font-bold text-sm" style={{ color: C.cream }}>
              Before You Use AI Support
            </p>
            <p className="text-[10px]" style={{ color: C.lightGreen }}>
              One-time acknowledgment required
            </p>
          </div>
        </div>

        <div className="px-5 py-4 space-y-4">
          {/* Intro */}
          <p className="text-xs leading-relaxed" style={{ color: C.darkGreen }}>
            Rooted 21's AI parenting coach is a powerful support tool — but it's important you understand what it is and isn't. Please read and acknowledge the following before continuing.
          </p>

          {/* Disclosures */}
          <div className="space-y-2.5">
            {DISCLOSURES.map((d, i) => (
              <div key={i} className="flex gap-3 rounded-xl p-3" style={{ background: C.white, border: `1px solid ${C.cream}` }}>
                <span className="text-base flex-shrink-0">{d.emoji}</span>
                <div>
                  <p className="text-xs font-bold mb-0.5" style={{ color: C.darkGreen }}>{d.title}</p>
                  <p className="text-[11px] leading-relaxed" style={{ color: C.mutedText }}>{d.body}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Crisis banner */}
          <div className="rounded-xl p-3 flex gap-2 items-start" style={{ background: "#FEF3EE", border: "1px solid #F4C9B8" }}>
            <AlertTriangle size={14} color="#B84C2A" className="flex-shrink-0 mt-0.5" />
            <p className="text-[11px] leading-relaxed" style={{ color: "#B84C2A" }}>
              <strong>Emergency?</strong> Call <strong>911</strong>. Mental health crisis? Call or text <strong>988</strong>. Do not rely on AI during an active emergency.
            </p>
          </div>

          {/* Legal links */}
          <p className="text-[11px] leading-relaxed" style={{ color: C.mutedText }}>
            By continuing, you agree to Rooted 21's{" "}
            <Link to="/legal" style={{ color: C.midGreen, fontWeight: "bold" }}>Terms of Service</Link>
            {" "}and{" "}
            <Link to="/legal" style={{ color: C.midGreen, fontWeight: "bold" }}>Privacy Policy</Link>.
          </p>

          {/* Checkbox */}
          <label
            className="flex items-start gap-3 p-3 rounded-xl cursor-pointer"
            style={{ background: checked ? "#EAF4EA" : C.white, border: `1.5px solid ${checked ? C.midGreen : C.cream}` }}
          >
            <input
              type="checkbox"
              checked={checked}
              onChange={e => setChecked(e.target.checked)}
              className="mt-0.5 flex-shrink-0"
              style={{ width: 16, height: 16, accentColor: C.midGreen }}
            />
            <p className="text-xs leading-relaxed" style={{ color: C.darkGreen }}>
              <strong>I understand</strong> that Rooted 21's AI is an informational support tool — not a licensed therapist, doctor, or attorney — and that I will seek professional help for medical, legal, or crisis situations.
            </p>
          </label>

          {/* Accept button */}
          <button
            onClick={handleAccept}
            disabled={!checked}
            className="w-full py-3.5 rounded-xl font-bold text-sm flex items-center justify-center gap-2 transition-all"
            style={{
              background: checked ? C.darkGreen : C.cream,
              color: checked ? "#fff" : C.mutedText,
              border: "none",
              cursor: checked ? "pointer" : "default",
            }}
          >
            <CheckCircle2 size={16} />
            I Understand — Continue to AI Support
          </button>

          <div className="pb-2" />
        </div>
      </div>
    </div>
  );
}