import { createClientFromRequest } from "npm:@base44/sdk@0.8.25";
import { jsPDF } from "npm:jspdf@4.2.1";

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: "Unauthorized" }, { status: 401 });

    const { items = [], filtersSummary = "All communications" } = await req.json();
    const safeItems = Array.isArray(items) ? items.slice(0, 1000) : [];
    const generatedAt = new Date().toLocaleString("en-US", { timeZone: "America/New_York", dateStyle: "full", timeStyle: "long" });
    const reportId = `COM-${Date.now().toString(36).toUpperCase()}`;

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;
    let y = 18;

    const green = [27, 68, 44];
    const mid = [88, 140, 100];
    const gold = [166, 124, 82];
    const text = [40, 35, 30];
    const gray = [115, 105, 95];
    const light = [245, 237, 226];

    function footer() {
      doc.setFontSize(7);
      doc.setTextColor(...gray);
      doc.text(`Rooted 21 Communication Audit Trail · ${reportId}`, margin, pageHeight - 7);
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - margin - 16, pageHeight - 7);
    }

    function pageBreak(space = 20) {
      if (y + space > pageHeight - 18) {
        footer();
        doc.addPage();
        y = 18;
      }
    }

    doc.setFillColor(...green);
    doc.roundedRect(margin, y, contentWidth, 28, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(255, 255, 255);
    doc.text("COMMUNICATION AUDIT TRAIL", pageWidth / 2, y + 11, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(245, 230, 200);
    doc.text("Co-parent messages · Agency email logs · Professional messages · Case meeting notes", pageWidth / 2, y + 19, { align: "center" });
    y += 38;

    doc.setFillColor(...light);
    doc.roundedRect(margin, y, contentWidth, 34, 2, 2, "F");
    const meta = [
      ["Report ID", reportId],
      ["Generated by", `${user.full_name || user.email} (${user.email})`],
      ["Generated at", generatedAt],
      ["Filter", filtersSummary],
      ["Records included", String(safeItems.length)],
    ];
    let metaY = y + 6;
    meta.forEach(([label, value]) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...mid);
      doc.text(`${label}:`, margin + 3, metaY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...text);
      doc.text(String(value || "—"), margin + 35, metaY);
      metaY += 5;
    });
    y += 43;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...green);
    doc.text("Chronological Thread", margin, y);
    y += 6;

    safeItems.forEach((item, index) => {
      const header = `${index + 1}. ${item.dateLabel || "No date"} · ${item.typeLabel || item.type || "Communication"}`;
      const title = item.title || "Untitled communication";
      const participants = item.participants || "Participants not specified";
      const body = item.body || "";
      const metaLine = item.meta || "";
      const bodyLines = doc.splitTextToSize(body, contentWidth - 8);
      const boxHeight = 21 + bodyLines.length * 4.2 + (metaLine ? 5 : 0);
      pageBreak(boxHeight + 4);

      doc.setDrawColor(...light);
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(margin, y, contentWidth, boxHeight, 2, 2, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...gold);
      doc.text(header, margin + 4, y + 5);
      doc.setFontSize(9);
      doc.setTextColor(...green);
      doc.text(doc.splitTextToSize(title, contentWidth - 8), margin + 4, y + 10);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...gray);
      doc.text(doc.splitTextToSize(participants, contentWidth - 8), margin + 4, y + 15);
      doc.setFontSize(8.5);
      doc.setTextColor(...text);
      doc.text(bodyLines, margin + 4, y + 21);
      if (metaLine) {
        doc.setFontSize(7);
        doc.setTextColor(...gray);
        doc.text(metaLine, margin + 4, y + boxHeight - 4);
      }
      y += boxHeight + 4;
    });

    if (safeItems.length === 0) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...gray);
      doc.text("No communications matched this export.", margin, y);
    }

    footer();
    const pdfBytes = doc.output("arraybuffer");
    const base64 = btoa(String.fromCharCode(...new Uint8Array(pdfBytes)));

    return Response.json({ success: true, base64, fileName: `Communication-Audit-Trail-${reportId}.pdf`, reportId, count: safeItems.length });
  } catch (error) {
    console.error("exportCommunicationAuditThread error:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});